-- Seed de Identity
--
-- O seed oficial roda no startup da aplicacao via DatabaseSeeder, porque o hash
-- da senha deve ser gerado pelo ASP.NET Core Identity e nao armazenado em texto
-- puro em script SQL.
--
-- Dados semeados de forma idempotente:
-- - Role: Gestor
-- - Role: Subordinado
-- - Usuario gestor padrao: ti@leveinvestimentos.com.br
-- - Senha inicial do gestor padrao: teste123
-- - MustChangePassword do gestor padrao: false
--
-- Para aplicar:
-- 1. Execute as migrations no banco.
-- 2. Inicie a aplicacao Web.
-- 3. O startup chama DatabaseSeeder.SeedAsync e cria roles/usuario ausentes.
